name: departure
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/logos/facebook.png
    - assets/logos/google.png
    - assets/logos/kakaotalk.png
    - assets/images/splash_img.jpg
    - assets/images/trophy.png
    - assets/images/crown.png
    - assets/images/치킨.jpg
    - assets/images/마라요리.jpg
    - assets/images/떡볶이.jpg
    - assets/images/파스타.jpg
    
    # - assets/images/리조또.jpg
    # - assets/images/피자.jpg
    # - assets/images/라멘.jpg
    # - assets/images/족발.jpg
    # - assets/images/고기덮밥.jpg
    # - assets/images/감자탕.jpg
    # - assets/images/김밥.jpg
    # - assets/images/찜닭.jpg
    # - assets/images/닭갈비.jpg
    # - assets/images/곱창전골.jpg
    # - assets/images/야채곱창.jpg
    # - assets/images/곱창구이.jpg
    # - assets/images/막창.jpg
    # - assets/images/돼지고기구이.jpg
    # - assets/images/초밥.jpg
    # - assets/images/돈까스.jpg
    # - assets/images/메밀소바.jpg
    # - assets/images/카레.jpg
    # - assets/images/함박스테이크.jpg
    # - assets/images/중화면요리.jpg
    # - assets/images/중화고기요리.jpg
    # - assets/images/중화해산물요리.jpg
    # - assets/images/회.jpg
    # - assets/images/닭발.jpg
    # - assets/images/아구찜.jpg
    # - assets/images/비빔밥.jpg
    # - assets/images/후토마키.jpg
    # - assets/images/텐동.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts: 
    - family: BMDH
      fonts:
      - asset: assets/fonts/BMDOHYEON_ttf.ttf
    - family: BMYS
      fonts:
      - asset: assets/fonts/BMYEONSUNG_ttf.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
